# Generated by Django 2.2 on 2021-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDetails',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('id', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('healthiness_label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipe_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecipeEmbeddings',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cleaned_title', models.TextField(blank=True, null=True)),
                ('cleaned_ingrs', models.TextField(blank=True, null=True)),
                ('id', models.TextField(blank=True, null=True)),
                ('tfidf_weight', models.TextField(blank=True, null=True)),
                ('topic', models.IntegerField(blank=True, null=True)),
                ('combined_vec', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipe_embeddings',
                'managed': True,
            },
        ),
    ]
