# Generated by Django 2.2 on 2021-02-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeembeddings',
            name='weighted_title_vec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
