# Generated by Django 2.2 on 2021-02-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210215_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesave',
            name='saved',
        ),
    ]
