# Generated by Django 2.2 on 2021-02-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_recipesave_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedetails',
            name='healthiness_label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
