# Generated by Django 2.2 on 2021-03-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeembeddings',
            name='ingr_vec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
