# Generated by Django 2.2 on 2021-03-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recipeembeddings_ingr_vec'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeembeddings',
            name='topic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
