# Generated by Django 2.2 on 2021-03-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recipeembeddings_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeembeddings',
            name='combined_vec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
