# Generated by Django 2.2 on 2021-04-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recipeembeddings_combined_vec'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeembeddings',
            name='recipe_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
