# Generated by Django 2.2 on 2021-04-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipeembeddings_recipe_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedetails',
            name='partition',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='url',
        ),
        migrations.RemoveField(
            model_name='recipeembeddings',
            name='ingr_vec',
        ),
        migrations.RemoveField(
            model_name='recipeembeddings',
            name='recipe_embedding',
        ),
        migrations.RemoveField(
            model_name='recipeembeddings',
            name='title_vec',
        ),
        migrations.RemoveField(
            model_name='recipeembeddings',
            name='weighted_ingr_vec',
        ),
        migrations.RemoveField(
            model_name='recipeembeddings',
            name='weighted_title_vec',
        ),
    ]
